### ISSUE TITLE
feat(gui): create menu bar outline

### ISSUE THREAD

**Issue by t-bre** [sufst/vcu-gui#58]
### Description
Create outline menu bar model.

### Tasks
- [x] Create application command manager (`juce::ApplicationCommandManager`) and command IDs.
- [x] Create 'View' and 'Window' menus.
- [x] Add main window as application command target.
