### ISSUE TITLE
feat(gui): about window

### ISSUE THREAD

**Issue by t-bre** [sufst/vcu-gui#67]
## Description
Add an 'About' window with app version information.

## Tasks
- [ ] Create new 'About' window.
- [ ] Add window to menu bar.
- [ ] Display app icon, title and version.
- [ ] Display latest commit hash at build time after version.
