### ISSUE TITLE
feat(gui): add custom font

### ISSUE THREAD

**Issue by t-bre** [sufst/vcu-gui#72]
### Description
Set the default GUI font to be 'Karla' (from SUFST website).

### Tasks
- [ ] Add a repo with the Karla font as a submodule.
- [ ] Work out a mechanism to embed the font into the `BinaryData` library.
- [ ] Integrate font into GUI.

### Notes
- Font is available [here](https://github.com/googlefonts/karla).
- Maybe want some other fonts from SUFST website?
